jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Delete transient artifacts of successful workflow
    permissions:
      actions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
      name: Delete Artifacts
      run: "python .github/workflows/delete_artifacts.py \\\n  -t ${{ secrets.GITHUB_TOKEN\
        \ }} \\\n  -a \"transient_.*\" \\\n  -r ${{ github.event.workflow_run.id }}\n"
name: Cleanup Transient Artifacts
on:
  repository_dispatch:
    types: trigger-ga___cleanup-transient-artifacts.yml
