jobs:
  build-nightly:
    if: github.repository == 'apache/systemds'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      id: meta
      name: Configure Docker metadata
      uses: docker/metadata-action@v5
      with:
        images: apache/systemds
        tags: 'type=raw,value=${{ matrix.image-pattern }}

          '
    - continue-on-error: true
      id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USER }}
    - continue-on-error: true
      id: docker_build
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/${{ matrix.docker-file }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        include:
        - docker-file: sysds.Dockerfile
          image-pattern: nightly
        - docker-file: pythonsysds.Dockerfile
          image-pattern: python-nightly
name: Docker Image CI and CD
on:
  repository_dispatch:
    types: trigger-ga___docker-cd.yml
