jobs:
  determine_test_coverage:
    name: Determine Test Coverage
    needs:
    - java_tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Maven Dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-test-

          '
    - continue-on-error: true
      name: Download all Jacoco Artifacts
      uses: actions/download-artifact@v4
      with:
        path: target
    - continue-on-error: true
      name: Merge Jacoco Artifacts
      run: mvn jacoco:merge
    - continue-on-error: true
      name: Process Classes
      run: mvn process-classes
    - continue-on-error: true
      name: Generate Code Coverage Report
      run: mvn jacoco:report
    - continue-on-error: true
      if: (github.repository_owner == 'apache') && (github.ref_name != 'main')
      name: Upload Jacoco Report Artifact PR
      uses: actions/upload-artifact@v4
      with:
        name: Java Code Coverage (Jacoco)
        path: target/site/jacoco
        retention-days: 7
    - continue-on-error: true
      if: (github.repository_owner == 'apache') && (github.ref_name == 'main')
      name: Upload Jacoco Report Artifact Main
      uses: actions/upload-artifact@v4
      with:
        name: Java Code Coverage (Jacoco)
        path: target/site/jacoco
        retention-days: 30
    - continue-on-error: true
      if: (github.repository_owner != 'apache')
      name: Upload Jacoco Report Artifact Fork
      uses: actions/upload-artifact@v4
      with:
        name: Java Code Coverage (Jacoco)
        path: target/site/jacoco
        retention-days: 3
  java_tests:
    name: ${{ matrix.tests }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      id: test
      name: ${{ matrix.tests }}
      uses: ./.github/action/
      with:
        test-to-run: ${{ matrix.tests }}
    - continue-on-error: true
      name: Clean Github Artifact Name of Asterisks
      run: 'ARTIFACT_NAME="transient_jacoco"

        ARTIFACT_NAME+="-${{ matrix.os }}"

        ARTIFACT_NAME+="-java-${{ matrix.java }}"

        ARTIFACT_NAME+="-${{ matrix.tests }}"

        ARTIFACT_NAME=${ARTIFACT_NAME//\*/x} # replace * with x

        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Save Java Test Coverage as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: target/jacoco.exec
        retention-days: 1
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        os:
        - ubuntu-latest
        tests:
        - org.apache.sysds.test.applications.**
        - '**.test.usertest.**'
        - '**.component.c**.**'
        - '**.component.e**.**,**.component.f**.**,**.component.m**.**'
        - '**.component.p**.**,**.component.t**.**'
        - '**.functions.a**.**,**.functions.binary.matrix.**,**.functions.binary.scalar.**,**.functions.binary.tensor.**'
        - '**.functions.blocks.**,**.functions.data.rand.**,'
        - '**.functions.countDistinct.**,**.functions.countDistinctApprox.**'
        - '**.functions.data.misc.**,**.functions.lineage.**'
        - '**.functions.compress.**,**.functions.data.tensor.**,**.functions.codegenalg.parttwo.**,**.functions.codegen.**,**.functions.caching.**'
        - '**.functions.binary.matrix_full_cellwise.**,**.functions.binary.matrix_full_other.**'
        - '**.functions.federated.algorithms.**,**.functions.federated.io.**,**.functions.federated.paramserv.**'
        - '**.functions.federated.transform.**'
        - '**.functions.federated.primitives.part1.** -Dtest-threadCount=1 -Dtest-forkCount=1'
        - '**.functions.federated.primitives.part2.** -Dtest-threadCount=1 -Dtest-forkCount=1'
        - '**.functions.federated.primitives.part3.** -Dtest-threadCount=1 -Dtest-forkCount=1'
        - '**.functions.federated.primitives.part4.** -Dtest-threadCount=1 -Dtest-forkCount=1'
        - '**.functions.federated.primitives.part5.** -Dtest-threadCount=1 -Dtest-forkCount=1'
        - '**.functions.federated.monitoring.**,**.functions.federated.multitenant.**'
        - '**.functions.federated.codegen.**,**.functions.federated.FederatedTestObjectConstructor'
        - '**.functions.codegenalg.partone.**'
        - '**.functions.builtin.part1.**'
        - '**.functions.builtin.part2.**'
        - '**.functions.frame.**,**.functions.indexing.**,**.functions.io.**,**.functions.iogen.**'
        - '**.functions.dnn.**'
        - '**.functions.paramserv.**'
        - '**.functions.recompile.**,**.functions.misc.**,**.functions.mlcontext.**'
        - '**.functions.nary.**,**.functions.quaternary.**'
        - '**.functions.parfor.**,**.functions.pipelines.**'
        - '**.functions.homomorphicEncryption.**'
        - '**.functions.unary.scalar.**,**.functions.updateinplace.**,**.functions.vect.**'
        - '**.functions.reorg.**,**.functions.rewrite.**,**.functions.ternary.**,**.functions.transform.**'
        - '**.functions.unary.matrix.**,**.functions.linearization.**,**.functions.jmlc.**'
    timeout-minutes: 30
name: Java Test
on:
  repository_dispatch:
    types: trigger-ga___javaTests.yml
