jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java ${{ matrix.java }} ${{ matrix.javadist }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ matrix.javadist }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build
      run: mvn package -P rat -B
    strategy:
      fail-fast: false
      matrix:
        java:
        - '11'
        javadist:
        - adopt
        os:
        - ubuntu-latest
name: LicenseCheck
on:
  repository_dispatch:
    types: trigger-ga___license.yml
