jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build the application, with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        always-auth: false
        architecture: x64
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      name: Install and run build
      run: 'npm install

        '
      working-directory: scripts/monitoring
    - continue-on-error: true
      name: Run tests
      run: 'npm test

        '
      working-directory: scripts/monitoring
    strategy:
      matrix:
        node-version:
        - lts/*
name: Test Monitoring UI Angular App
on:
  repository_dispatch:
    types: trigger-ga___monitoringUITests.yml
