jobs:
  test:
    name: ${{ matrix.os }} Java ${{ matrix.java }} ${{ matrix.javadist }} Python ${{
      matrix.python-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java ${{ matrix.java }} ${{ matrix.javadist }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ matrix.javadist }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Pip Dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('src/main/python/setup.py')
          }}
        path: ~/.cache/pip
    - continue-on-error: true
      name: Cache Datasets
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mnist-${{ hashFiles('src/main/python/systemds/examples/tutorials/mnist.py')
          }}-${{ hashFiles('src/main/python/systemds/examples/tutorials/adult.py')
          }}
        path: 'src/main/python/systemds/examples/tutorials/mnist

          src/main/python/systemds/examples/tutorials/adult/data.zip

          '
    - continue-on-error: true
      name: Cache Deb Dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ hashFiles('.github/workflows/python.yml') }}
        path: /var/cache/apt/archives
    - continue-on-error: true
      name: Maven clean & package
      run: mvn -ntp clean package -P distribution -B
    - continue-on-error: true
      name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Install pip Dependencies
      run: "# Install pip twice to update past the versions.\npip install --upgrade\
        \ pip \npip install --upgrade pip\npip install wheel\npip install numpy py4j\
        \ scipy scikit-learn requests pandas unittest-parallel\n"
    - continue-on-error: true
      name: Build Python Package
      run: 'cd src/main/python

        python create_python_dist.py

        '
    - continue-on-error: true
      name: Run all python tests
      run: 'export SYSTEMDS_ROOT=$(pwd)

        export PATH=$SYSTEMDS_ROOT/bin:$PATH

        export SYSDS_QUIET=1

        export LOG4JPROP=$SYSTEMDS_ROOT/src/test/resources/log4j.properties

        cd src/main/python

        unittest-parallel -t . -s tests

        # python -m unittest discover -s tests -p ''test_*.py''

        echo "Exit Status: " $?

        '
    - continue-on-error: true
      name: Run all python tests no environment
      run: 'export LOG4JPROP=$(pwd)/src/test/resources/log4j.properties

        cd src/main/python

        unittest-parallel -t . -s tests

        # python -m unittest discover -s tests -p ''test_*.py''

        echo "Exit Status: " $?

        '
    - continue-on-error: true
      name: Run Federated Python Tests
      run: 'export SYSTEMDS_ROOT=$(pwd)

        export PATH=$SYSTEMDS_ROOT/bin:$PATH

        cd src/main/python

        ./tests/federated/runFedTest.sh

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - '11'
        javadist:
        - adopt
        os:
        - ubuntu-latest
        python-version:
        - 3.8
name: Python Test
on:
  repository_dispatch:
    types: trigger-ga___python.yml
